import { Geist, Geist_Mono, Inter, Audiowide } from "next/font/google"
import "./globals.css"
import SmoothScroll from "./components/SmoothScroll"
import Dotted from "./components/Dotted"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

const audiowide = Audiowide({
  variable: "--font-audiowide",
  weight: "400",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${audiowide.variable} antialiased`}
      >
        <SmoothScroll>
          <Dotted />

          {children}
        </SmoothScroll>
      </body>
    </html>
  )
}
